# Dynmap-Diag configuration
#
update:
  # Seconds between checks for chunk updates
  chunkperiod: 30

chunklayer:
  name: "Chunks Loaded"
  # Make layer hidden by default
  hidebydefault: true
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 2
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0
  
chunkstyle:
  strokeColor: "#00007F"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#00007F"
  fillOpacity: 0.35
  
